title: aj
tagline: My life is a hexdump 
permalink: /posts/:title/
exclude: [Gemfile, Gemfile.lock, README.md, vendor, org, .hyde.el]
markdown: kramdown
kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
baseurl: ""
editor: emacs .
disqus_sitename: allysonjuliancom
gems: [jekyll-gist]
