title: aj
tagline: My life is a hexdump
permalink: /posts/:title/
exclude: [Gemfile, Gemfile.lock, README.md, vendor, org, .hyde.el, server.sh]
markdown: kramdown
kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
baseurl: ""
url: https://allysonjulian.com
editor: emacs .
disqus_sitename: allysonjuliancom
plugins: [jekyll-gist]
